
# JSONPlaceholder — analiza danych z API

Notebook pobiera dane z publicznego API JSONPlaceholder, analizuje aktywność użytkowników, posty, komentarze oraz realizację zadań, a następnie przedstawia wyniki na wykresach.

**Źródło danych:** [JSONPlaceholder](https://jsonplaceholder.typicode.com/)

**Dane:** `/users`, `/posts`, `/comments`, `/todos`

**Narzędzia:** Google Colab (Jupyter Notebook), Python

**Biblioteki:** pandas, requests, plotly

## Spis treści

1. Przygotowanie środowiska
2. Pobieranie danych
3. Eksploracja danych
4. Walidacja danych
5. Metryki i analiza
6. Wizualizacje
7. Wnioski analityczne

*Uwaga: JSONPlaceholder udostępnia przykładowe dane demonstracyjne, a nie rzeczywistą aktywność użytkowników.*


## 01. Przygotowanie środowiska

W projekcie korzystam z biblioteki requests do pobierania danych z API, pandas do analizy danych tabelarycznych oraz plotly do tworzenia interaktywnych wizualizacji.

In [15]:
import requests
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Paleta kolorów używana na wykresach
BG_COLOR = "#111827"
TEXT_COLOR = "#F9FAFB"
ACCENT_COLOR = "#FFC629"
SECONDARY_COLOR = "#CBD5E1"
TRACK_COLOR = "#1F2937"
TEAL_COLOR = "#2DD4BF"
BRONZE_COLOR = "#E87B00"

## 02. Pobieranie danych
## 02. Pobieranie danych

Pobieram dane z czterech endpointów API: użytkowników, postów, komentarzy i zadań. Odpowiedzi przekształcam w obiekty DataFrame, aby umożliwić dalszą analizę z wykorzystaniem biblioteki pandas. Ustawiam również limit czasu zapytań na 10 sekund i stosuję metodę `raise_for_status()`, która pozwala wykryć błędy HTTP i sprawdzić, czy pobieranie danych przebiegło prawidłowo.

In [16]:

BASE_URL = "https://jsonplaceholder.typicode.com"

users_response = requests.get(f"{BASE_URL}/users", timeout=10)
posts_response = requests.get(f"{BASE_URL}/posts", timeout=10)
comments_response = requests.get(f"{BASE_URL}/comments", timeout=10)
todos_response = requests.get(f"{BASE_URL}/todos", timeout=10)

users_response.raise_for_status()
posts_response.raise_for_status()
comments_response.raise_for_status()
todos_response.raise_for_status()

users = pd.DataFrame(users_response.json())
posts = pd.DataFrame(posts_response.json())
comments = pd.DataFrame(comments_response.json())
todos = pd.DataFrame(todos_response.json())

print("Dane zostały pobrane pomyślnie.")

# Zestawienie tabel wykorzystywane w eksploracji i walidacji danych
datasets = {
    "Użytkownicy": users,
    "Posty": posts,
    "Komentarze": comments,
    "Zadania": todos
}

Dane zostały pobrane pomyślnie.

## 03. Eksploracja danych

W tej sekcji przeprowadzam wstępną eksplorację czterech zbiorów danych. Za pomocą metody `info()` sprawdzam liczbę rekordów, kolumny, typy danych oraz liczbę wartości niepustych. Następnie wykorzystuję metodę `head()`, aby wyświetlić pierwsze rekordy każdej tabeli i zapoznać się z ich strukturą oraz przykładową zawartością.

In [17]:

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    df.info()

--- Użytkownicy ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10 non-null     int64
 1   name      10 non-null     object
 2   username  10 non-null     object
 3   email     10 non-null     object
 4   address   10 non-null     object
 5   phone     10 non-null     object
 6   website   10 non-null     object
 7   company   10 non-null     object
dtypes: int64(1), object(7)
memory usage: 772.0+ bytes

--- Posty ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  100 non-null    int64
 1   id      100 non-null    int64
 2   title   100 non-null    object
 3   body    100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB

--- Komentarze ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   postId  500 non-null    int64
 1   id      500 non-null    int64
 2   name    500 non-null    object
 3   email   500 non-null    object
 4   body    500 non-null    object
dtypes: int64(2), object(3)
memory usage: 19.7+ KB

--- Zadania ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     200 non-null    int64
 1   id         200 non-null    int64
 2   title      200 non-null    object
 3   completed  200 non-null    bool
dtypes: bool(1), int64(2), object(1)
memory usage: 5.0+ KB

In [18]:

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    display(df.head())

--- Użytkownicy ---

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

--- Posty ---

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

--- Komentarze ---

,postId,id,name,email,body
0,1,1,id labore ex et quam laborum,Eliseo@gardner.biz,laudantium enim quasi est quidem magnam volupt...
1,1,2,quo vero reiciendis velit similique earum,Jayne_Kuhic@sydney.com,est natus enim nihil est dolore omnis voluptat...
2,1,3,odio adipisci rerum aut animi,Nikita@garfield.biz,quia molestiae reprehenderit quasi aspernatur\...
3,1,4,alias odio sit,Lew@alysha.tv,non et atque\noccaecati deserunt quas accusant...
4,1,5,vero eaque aliquid doloribus et culpa,Hayden@althea.biz,harum non quasi et ratione\ntempore iure ex vo...

--- Zadania ---

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

## 04. Walidacja danych
Sprawdzam poprawność pobranych danych, porównując rozmiary tabel z oczekiwanymi wartościami. Dodatkowo weryfikuję występowanie brakujących wartości i powtarzających się identyfikatorów. Wykorzystuję instrukcję `assert()`, aby automatycznie wykrywać niezgodności i przerwać wykonywanie kodu w przypadku wykrycia błędów. Dzięki temu mogę upewnić się, że dane spełniają podstawowe założenia przed rozpoczęciem dalszej analizy.

In [19]:

expected_shapes = {
    "Użytkownicy": (10, 8),
    "Posty": (100, 4),
    "Komentarze": (500, 5),
    "Zadania": (200, 4)
}

for name, df in datasets.items():
    expected_shape = expected_shapes[name]
    shape_ok = df.shape == expected_shape
    missing_values = df.isna().sum().sum()
    duplicate_ids = df["id"].duplicated().sum()

    print(f"\n--- {name} ---")
    print(f"Liczba wierszy: {df.shape[0]} (oczekiwano: {expected_shape[0]})")
    print(f"Liczba kolumn: {df.shape[1]} (oczekiwano: {expected_shape[1]})")
    print(f"Brakujące wartości: {missing_values}")
    print(f"Duplikaty identyfikatorów: {duplicate_ids}")
    print(f"Zgodność rozmiaru tabeli: {'OK' if shape_ok else 'BŁĄD'}")

    assert shape_ok, f"{name}: niezgodna liczba wierszy lub kolumn"
    assert missing_values == 0, f"{name}: wykryto brakujące wartości"
    assert duplicate_ids == 0, f"{name}: wykryto powtarzające się identyfikatory"

print("\nWalidacja zakończona pomyślnie.")

--- Użytkownicy ---
Liczba wierszy: 10 (oczekiwano: 10)
Liczba kolumn: 8 (oczekiwano: 8)
Brakujące wartości: 0
Duplikaty identyfikatorów: 0
Zgodność rozmiaru tabeli: OK

--- Posty ---
Liczba wierszy: 100 (oczekiwano: 100)
Liczba kolumn: 4 (oczekiwano: 4)
Brakujące wartości: 0
Duplikaty identyfikatorów: 0
Zgodność rozmiaru tabeli: OK

--- Komentarze ---
Liczba wierszy: 500 (oczekiwano: 500)
Liczba kolumn: 5 (oczekiwano: 5)
Brakujące wartości: 0
Duplikaty identyfikatorów: 0
Zgodność rozmiaru tabeli: OK

--- Zadania ---
Liczba wierszy: 200 (oczekiwano: 200)
Liczba kolumn: 4 (oczekiwano: 4)
Brakujące wartości: 0
Duplikaty identyfikatorów: 0
Zgodność rozmiaru tabeli: OK

Walidacja zakończona pomyślnie.


## 05. Metryki i analiza
W tej sekcji analizuję dostępne dane, obliczam podstawowe metryki i identyfikuję najważniejsze obserwacje. Celem jest porównanie aktywności użytkowników, liczby publikowanych postów i komentarzy oraz stopnia realizacji zadań, a następnie sformułowanie konkretnych wniosków analitycznych.
### 5.1 Podstawowe metryki
Obliczam liczbę użytkowników, postów, komentarzy i zadań, a także sprawdzam, ile zadań zostało ukończonych i jaki jest ogólny wskaźnik ich realizacji. Wyniki stanowią punkt wyjścia do dalszej analizy danych.

In [20]:

total_users = users["id"].nunique()
total_posts = posts["id"].nunique()
total_comments = comments["id"].nunique()
total_tasks = todos["id"].nunique()

completed_tasks = todos["completed"].sum()
incomplete_tasks = total_tasks - completed_tasks

completion_rate = todos["completed"].mean() * 100

print(f"Liczba użytkowników: {total_users}")
print(f"Liczba postów: {total_posts}")
print(f"Liczba komentarzy: {total_comments}")
print(f"Liczba zadań: {total_tasks}")
print(f"Ukończone zadania: {completed_tasks}")
print(f"Nieukończone zadania: {incomplete_tasks}")
print(f"Wskaźnik realizacji zadań: {completion_rate:.0f}%")

Liczba użytkowników: 10
Liczba postów: 100
Liczba komentarzy: 500
Liczba zadań: 200
Ukończone zadania: 90
Nieukończone zadania: 110
Wskaźnik realizacji zadań: 45%

### 5.2 Analiza aktywności użytkowników

Zliczam posty opublikowane przez każdego użytkownika, a następnie za pomocą funkcji `merge()` z biblioteki pandas łączę wyniki z danymi użytkowników, dopasowując ich identyfikatory. Dzięki temu mogę przypisać liczbę postów do konkretnych osób i porównać ich aktywność. Wszyscy użytkownicy mają po 10 postów.

In [21]:

posts_per_user = (
    posts.groupby("userId")
    .size()
    .reset_index(name="post_count")
)

posts_per_user = posts_per_user.merge(
    users[["id", "name"]],
    left_on="userId",
    right_on="id"
)

posts_per_user = posts_per_user[
    ["userId", "name", "post_count"]
].sort_values("post_count", ascending=False)

display(posts_per_user)

   userId                      name  post_count
0       1             Leanne Graham          10
1       2              Ervin Howell          10
2       3          Clementine Bauch          10
3       4          Patricia Lebsack          10
4       5          Chelsey Dietrich          10
5       6      Mrs. Dennis Schulist          10
6       7           Kurtis Weissnat          10
7       8  Nicholas Runolfsdottir V          10
8       9           Glenna Reichert          10
9      10        Clementina DuBuque          10


### 5.3 Analiza komentarzy
Zliczam komentarze przypisane do poszczególnych postów, a następnie łączę wyniki z danymi o postach, również za pomocą funkcji `merge()`, aby ustalić ich autorów. Grupuję wyniki według użytkowników i sumuję komentarze pod ich postami, co pozwala porównać liczbę komentarzy przypisanych do publikacji poszczególnych osób.

In [22]:

comments_per_post = (
    comments.groupby("postId")
    .size()
    .reset_index(name="comment_count")
)

posts_with_comments = posts.merge(
    comments_per_post,
    left_on="id",
    right_on="postId",
    how="left"
)

comments_per_user = (
    posts_with_comments.groupby("userId")
    .agg(total_comments=("comment_count", "sum"))
    .reset_index()
)

comments_per_user = comments_per_user.merge(
    users[["id", "name"]],
    left_on="userId",
    right_on="id",
    how="left"
)

comments_per_user = (
    comments_per_user[["userId", "name", "total_comments"]]
    .sort_values(
        ["total_comments", "name"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

### 5.4 Analiza zadań
Analizuję realizację zadań przez poszczególnych użytkowników. Obliczam liczbę wszystkich, ukończonych i nieukończonych zadań oraz procent ich realizacji. Następnie łączę wyniki z danymi użytkowników i sortuję je według wskaźnika ukończenia, aby porównać wyniki poszczególnych osób.

In [23]:

tasks_per_user = (
    todos.groupby("userId")
    .agg(
        total_tasks=("id", "count"),
        completed_tasks=("completed", "sum")
    )
    .reset_index()
)

tasks_per_user["incomplete_tasks"] = (
    tasks_per_user["total_tasks"]
    - tasks_per_user["completed_tasks"]
)

tasks_per_user["completion_rate"] = (
    tasks_per_user["completed_tasks"]
    / tasks_per_user["total_tasks"]
    * 100
).round(1)

tasks_per_user = tasks_per_user.merge(
    users[["id", "name"]],
    left_on="userId",
    right_on="id"
)

tasks_per_user = tasks_per_user[
    [
        "userId",
        "name",
        "total_tasks",
        "completed_tasks",
        "incomplete_tasks",
        "completion_rate"
    ]
].sort_values("completion_rate", ascending=False)

display(tasks_per_user)

,userId,name,total_tasks,completed_tasks,incomplete_tasks,completion_rate
9,10,Clementina DuBuque,20,12,8,60.0
4,5,Chelsey Dietrich,20,12,8,60.0
7,8,Nicholas Runolfsdottir V,20,11,9,55.0
0,1,Leanne Graham,20,11,9,55.0
6,7,Kurtis Weissnat,20,9,11,45.0
1,2,Ervin Howell,20,8,12,40.0
8,9,Glenna Reichert,20,8,12,40.0
2,3,Clementine Bauch,20,7,13,35.0
5,6,Mrs. Dennis Schulist,20,6,14,30.0
3,4,Patricia Lebsack,20,6,14,30.0

### 5.5 Zestawienie i ranking aktywności użytkowników

Łączę liczbę postów opublikowanych przez każdego użytkownika z liczbą komentarzy pod jego publikacjami. Na podstawie połączonych danych tworzę zestawienie aktywności oraz wybieram trzy pierwsze osoby do wizualizacji podium. W tym zbiorze wszyscy użytkownicy mają takie same wyniki, dlatego kolejność rozstrzyga nazwa.

In [24]:

user_activity = posts_per_user.merge(
    comments_per_user[["userId", "total_comments"]],
    on="userId",
    how="left"
)


user_activity = (
    user_activity[["userId", "name", "post_count", "total_comments"]]
    .sort_values(
        ["post_count", "total_comments", "name"],
        ascending=[False, False, True]
    )
    .reset_index(drop=True)
)

display(user_activity)


top_3_users = user_activity.head(3).copy()
top_3_users["position"] = [1, 2, 3]

   userId                      name  post_count  total_comments
0       5          Chelsey Dietrich          10              50
1      10        Clementina DuBuque          10              50
2       3          Clementine Bauch          10              50
3       2              Ervin Howell          10              50
4       9           Glenna Reichert          10              50
5       7           Kurtis Weissnat          10              50
6       1             Leanne Graham          10              50
7       6      Mrs. Dennis Schulist          10              50
8       8  Nicholas Runolfsdottir V          10              50
9       4          Patricia Lebsack          10              50


## 06. Wizualizacje
Prezentuję najważniejsze wyniki przeprowadzonych analiz w formie wykresów. Dzięki wizualizacjom łatwiej zauważyć proporcje, porównać wyniki i zidentyfikować najciekawsze obserwacje dotyczące użytkowników oraz realizacji zadań.
### 6.1 Podsumowanie realizacji zadań
Przedstawiam udział zadań ukończonych i nieukończonych na wykresie pierścieniowym. Wykres pozwala szybko ocenić ogólny poziom realizacji zadań, który w analizowanym zbiorze wynosi 45%.

In [25]:


task_status = pd.DataFrame({
    "Status": ["Zadania ukończone", "Zadania nieukończone"],
    "Zadania": [completed_tasks, incomplete_tasks]
})


fig = px.pie(
    task_status,
    names="Status",
    values="Zadania",
    hole=0.65,
    color="Status",
    color_discrete_map={
        "Zadania ukończone": ACCENT_COLOR,
        "Zadania nieukończone": SECONDARY_COLOR
    }
)


fig.update_traces(
    texttemplate="%{value}",
    textposition="inside",
    insidetextorientation="horizontal",
    textfont=dict(
        family="Arial",
        size=14,
        color=BG_COLOR
    ),
    hovertemplate=(
        "%{label}: %{value} zadań "
        "(%{percent})<extra></extra>"
    ),
    sort=False,
    marker=dict(
        line=dict(color=BG_COLOR, width=3)
    ),
    domain=dict(
        x=[0.15, 0.85],
        y=[0.12, 0.90]
    )
)


fig.update_layout(
    annotations=[{
        "text": f"{completion_rate:.0f}%",
        "x": 0.5,
        "y": 0.51,
        "font": dict(
            family="Arial",
            size=30,
            color=TEXT_COLOR
        ),
        "showarrow": False
    }],
    title=dict(
        text="Podsumowanie realizacji zadań",
        font=dict(
            family="Arial",
            size=20,
            color=TEXT_COLOR
        ),
        x=0.04,
        xanchor="left"
    ),
    font=dict(
        family="Arial",
        color=TEXT_COLOR,
        size=12
    ),
    paper_bgcolor=BG_COLOR,
    plot_bgcolor=BG_COLOR,
    height=450,
    margin=dict(t=65, b=65, l=45, r=45),
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=0.01,
        xanchor="center",
        x=0.5,
        font=dict(
            family="Arial",
            size=12,
            color=TEXT_COLOR
        )
    )
)

fig.show()

**Wniosek:** wykonanych jest 90 z 200 zadań, czyli 45%. Ponad połowa zadań (55%) pozostaje niewykonana.


### 6.2 Ukończenie zadań przez użytkowników
Porównuję procent ukończonych zadań dla poszczególnych użytkowników. Wyniki przedstawiam na poziomym wykresie słupkowym, posortowanym od najwyższego do najniższego wskaźnika realizacji. Dzięki temu łatwo zauważyć różnice między użytkownikami i wskazać osoby z najwyższym oraz najniższym wynikiem.

In [26]:



user_completion = tasks_per_user.sort_values(
    "completion_rate",
    ascending=False
).copy()

fig = go.Figure()


fig.add_trace(go.Bar(
    x=[100] * len(user_completion),
    y=user_completion["name"],
    orientation="h",
    marker=dict(
        color=TRACK_COLOR,
        cornerradius=10
    ),
    hoverinfo="skip",
    showlegend=False
))


fig.add_trace(go.Bar(
    x=user_completion["completion_rate"],
    y=user_completion["name"],
    orientation="h",
    marker=dict(
        color=TEAL_COLOR,
        cornerradius=10
    ),
    hovertemplate=(
        "<b>%{y}</b><br>"
        "Odsetek ukończenia: %{x:.0f}%"
        "<extra></extra>"
    ),
    showlegend=False
))


for _, row in user_completion.iterrows():
    fig.add_annotation(
        x=102,
        y=row["name"],
        text=f"{row['completion_rate']:.0f}%",
        showarrow=False,
        xanchor="left",
        font=dict(
            family="Arial",
            size=12,
            color=TEXT_COLOR
        )
    )


fig.update_layout(
    title=dict(
        text="Ukończenie zadań przez użytkowników",
        font=dict(
            family="Arial",
            size=18,
            color=TEXT_COLOR
        ),
        x=0.04,
        xanchor="left"
    ),
    barmode="overlay",
    bargap=0.45,
    paper_bgcolor=BG_COLOR,
    plot_bgcolor=BG_COLOR,
    font=dict(
        family="Arial",
        size=12,
        color=TEXT_COLOR
    ),
    xaxis=dict(
        range=[0, 110],
        visible=False,
        fixedrange=True
    ),
    yaxis=dict(
        title=None,
        showgrid=False,
        showline=False,
        ticks="",
        automargin=True,
        fixedrange=True,
        autorange="reversed",
        ticklabelstandoff=12
    ),
    showlegend=False,
    height=450,
    margin=dict(t=65, b=25, l=200, r=45)
)

fig.show()

**Wniosek:** odsetek wykonanych zadań mocno różni się między użytkownikami, od 30% do 60%.
Najwyższy wynik mają Clementina DuBuque i Chelsey Dietrich (po 60%), a najniższy Mrs. Dennis Schulist i Patricia Lebsack (po 30%).
Czterech użytkowników jest powyżej średniej 45%, jeden dokładnie na średniej, a pięciu poniżej.

### 6.3 Podium aktywności użytkowników
Przedstawiam trzech użytkowników w formie podium, uwzględniając liczbę opublikowanych postów i komentarzy pod ich publikacjami. Wizualizacja pozwala w przejrzysty sposób porównać wybrane osoby pod względem aktywności. Ze względu na równomierny rozkład danych wszyscy użytkownicy mają takie same wyniki.

In [27]:


podium = top_3_users.copy()


podium["display_order"] = podium["position"].map({
    2: 1,
    1: 2,
    3: 3
})


podium["podium_height"] = podium["position"].map({
    1: 3,
    2: 2,
    3: 1
})


podium_colors = {
    1: ACCENT_COLOR,
    2: SECONDARY_COLOR,
    3: BRONZE_COLOR
}

podium["color"] = podium["position"].map(podium_colors)


fig = px.bar(
    podium,
    x="display_order",
    y="podium_height",
    custom_data=["name", "post_count", "total_comments", "position"],
    title="Podium aktywności użytkowników"
)


fig.update_traces(
    marker_color=podium["color"].tolist(),
    marker_line_width=0,
    hovertemplate=(
        "<b>%{customdata[0]}</b><br>"
        "Liczba postów: %{customdata[1]}<br>"
        "Komentarze pod postami: %{customdata[2]}"
        "<extra></extra>"
    )
)


for _, row in podium.iterrows():
    fig.add_annotation(
        x=row["display_order"],
        y=row["podium_height"] / 2,
        text=row["name"],
        showarrow=False,
        font=dict(
            size=14,
            color="#111827"
        )
    )


medals = {
    1: "🥇",
    2: "🥈",
    3: "🥉"
}

for _, row in podium.iterrows():
    fig.add_annotation(
        x=row["display_order"],
        y=row["podium_height"] + 0.12,
        text=medals[row["position"]],
        showarrow=False,
        font=dict(size=28)
    )


    fig.add_annotation(
        x=row["display_order"],
        y=-0.18,
        text=f"{row['post_count']} postów",
        showarrow=False,
        font=dict(
            size=13,
            color=TEXT_COLOR
        )
    )


fig.update_layout(
    xaxis=dict(
        tickmode="array",
        tickvals=[1, 2, 3],
        ticktext=["", "", ""],
        showgrid=False,
        zeroline=False,
        showticklabels=False,
        title=None,
        fixedrange=True
    ),
    yaxis=dict(
        visible=False,
        range=[-0.4, 3.6],
        fixedrange=True
    ),
    showlegend=False,
    plot_bgcolor=BG_COLOR,
    paper_bgcolor=BG_COLOR,
    font=dict(
        family="Arial",
        color=TEXT_COLOR
    ),
    title_font=dict(
        size=18,
        color=TEXT_COLOR
    ),
    height=520,
    margin=dict(t=80, b=65, l=30, r=30)
)

fig.show()

**Uwaga o rankingu:** użytkownicy są uporządkowani według liczby postów, następnie według liczby otrzymanych komentarzy, a na końcu alfabetycznie według nazwy.
W tym zbiorze każdy użytkownik ma 10 postów i 50 komentarzy, więc o miejscach na podium zdecydowała wyłącznie nazwa.
Podium ilustruje więc strukturę danych, a nie różnice w aktywności użytkowników.

## 07. Wnioski analityczne

- **Realizacja zadań:** ogólny odsetek wykonanych zadań wynosi 45% (90 z 200).
- **Różnice między użytkownikami:** odsetek wykonanych zadań waha się od 30% do 60%, więc jest to jedyna metryka, która wyraźnie różnicuje użytkowników.
- **Posty i komentarze:** każdy użytkownik ma 10 postów, a każdy post 5 komentarzy (50 komentarzy na użytkownika), więc te metryki nie pokazują różnic w aktywności.
- **Charakter danych:** JSONPlaceholder to syntetyczny zbiór demonstracyjny. Wyniki pokazują strukturę danych i umiejętność ich analizy, a nie rzeczywiste zachowania użytkowników.